#+Title: Unicode declarations for LaTeX documents.
#+Author: Mark Armstrong
#+Description: A list of unicode character declarations for LaTeX
#+Property: header-args:latex :tangle unicode.sty

* About this file

In order to write LaTeX documents using unicode in the source code,
we must often tell LaTeX what we want the unicode characters
to be rendered as.

There are two ways to do this;
- ~\DeclareUnicodeCharacter~; this command does not work with
  XeLaTeX or LuaLaTeX, which I use.
- ~\newunicodechar~; this command is provided by the
  newunicodechar package, which may not be pre-installed for all LaTeX users.

I choose the second evil :).
#+begin_src latex
\usepackage{newunicodechar}
#+end_src

The unicode-math package should also be used.
#+begin_src latex
\usepackage{unicode-math}
#+end_src

* Blackboard and math caligraphic letters       :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Blackboard letters
%---------------------------------------------------------------------
\newunicodechar{𝔹}{\ensuremath{\mathrm{𝔹}}}
\newunicodechar{ℕ}{\ensuremath{\mathrm{ℕ}}}
\newunicodechar{ℝ}{\ensuremath{\mathrm{ℝ}}}
\newunicodechar{ℤ}{\ensuremath{\mathrm{ℤ}}}
#+end_src

#+begin_src latex
%---------------------------------------------------------------------
% Math caligraphic letters
%---------------------------------------------------------------------
\newunicodechar{𝒫}{\ensuremath{\mathcal{P}}}
#+end_src

* Greek letters                                 :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Greek letters
%---------------------------------------------------------------------
\newunicodechar{α}{\ensuremath{\mathrm{α}}}
\newunicodechar{δ}{\ensuremath{\mathrm{δ}}}
\newunicodechar{Δ}{\ensuremath{\mathrm{Δ}}}
\newunicodechar{ε}{\ensuremath{\mathrm{ε}}}
\newunicodechar{ι}{\ensuremath{\mathrm{ι}}}
\newunicodechar{λ}{\ensuremath{\mathrm{λ}}}
\newunicodechar{μ}{\ensuremath{\mathrm{μ}}}
\newunicodechar{σ}{\ensuremath{\mathrm{σ}}}
\newunicodechar{Σ}{\ensuremath{\mathrm{Σ}}}
#+end_src

* Subscripts and superscripts                   :incomplete:

Note that while the alphabetic lists are complete,
*there are missing letters*,
because for some reason Unicode does not have characters
for every letter subscript and superscript. :(

** Numberic subscripts                         :complete:

#+begin_src latex
%---------------------------------------------------------------------
% Numerical subscripts
%---------------------------------------------------------------------
\newunicodechar{₀}{\ensuremath{{}_{0}}}
\newunicodechar{₁}{\ensuremath{{}_{1}}}
\newunicodechar{₂}{\ensuremath{{}_{2}}}
\newunicodechar{₃}{\ensuremath{{}_{3}}}
\newunicodechar{₄}{\ensuremath{{}_{4}}}
\newunicodechar{₅}{\ensuremath{{}_{5}}}
\newunicodechar{₆}{\ensuremath{{}_{6}}}
\newunicodechar{₇}{\ensuremath{{}_{7}}}
\newunicodechar{₈}{\ensuremath{{}_{8}}}
\newunicodechar{₉}{\ensuremath{{}_{9}}}
#+end_src

** Alphabetic subscripts                       :complete:

#+begin_src latex
%---------------------------------------------------------------------
% Alphabetical subscripts
%---------------------------------------------------------------------
\newunicodechar{ₐ}{\ensuremath{{}_{a}}}
\newunicodechar{ₑ}{\ensuremath{{}_{e}}}
\newunicodechar{ₕ}{\ensuremath{{}_{h}}}
\newunicodechar{ᵢ}{\ensuremath{{}_{i}}}
\newunicodechar{ⱼ}{\ensuremath{{}_{j}}}
\newunicodechar{ₖ}{\ensuremath{{}_{k}}}
\newunicodechar{ₗ}{\ensuremath{{}_{l}}}
\newunicodechar{ₘ}{\ensuremath{{}_{m}}}
\newunicodechar{ₙ}{\ensuremath{{}_{n}}}
\newunicodechar{ₒ}{\ensuremath{{}_{o}}}
\newunicodechar{ₚ}{\ensuremath{{}_{p}}}
\newunicodechar{ᵣ}{\ensuremath{{}_{r}}}
\newunicodechar{ₛ}{\ensuremath{{}_{s}}}
\newunicodechar{ₜ}{\ensuremath{{}_{t}}}
\newunicodechar{ᵤ}{\ensuremath{{}_{u}}}
\newunicodechar{ᵥ}{\ensuremath{{}_{v}}}
\newunicodechar{ₓ}{\ensuremath{{}_{x}}}
#+end_src

** Alphabetic superscripts

#+begin_src latex
%---------------------------------------------------------------------
% Alphabetical superscripts
%---------------------------------------------------------------------
\newunicodechar{ᵃ}{\ensuremath{{}^{a}}}
\newunicodechar{ᵇ}{\ensuremath{{}^{b}}}
\newunicodechar{ᶜ}{\ensuremath{{}^{c}}}
\newunicodechar{ᵈ}{\ensuremath{{}^{d}}}
\newunicodechar{ᵉ}{\ensuremath{{}^{e}}}
\newunicodechar{ᶠ}{\ensuremath{{}^{f}}}
\newunicodechar{ᵍ}{\ensuremath{{}^{g}}}
\newunicodechar{ʰ}{\ensuremath{{}^{h}}}
\newunicodechar{ⁱ}{\ensuremath{{}^{i}}}
\newunicodechar{ʲ}{\ensuremath{{}^{j}}}
\newunicodechar{ᵏ}{\ensuremath{{}^{k}}}
\newunicodechar{ˡ}{\ensuremath{{}^{l}}}
\newunicodechar{ᵐ}{\ensuremath{{}^{m}}}
\newunicodechar{ⁿ}{\ensuremath{{}^{n}}}
\newunicodechar{ᵒ}{\ensuremath{{}^{o}}}
\newunicodechar{ᵖ}{\ensuremath{{}^{p}}}
\newunicodechar{ʳ}{\ensuremath{{}^{r}}}
\newunicodechar{ˢ}{\ensuremath{{}^{s}}}
\newunicodechar{ᵗ}{\ensuremath{{}^{t}}}
\newunicodechar{ᵘ}{\ensuremath{{}^{u}}}
\newunicodechar{ᵛ}{\ensuremath{{}^{v}}}
\newunicodechar{ʷ}{\ensuremath{{}^{q}}}
\newunicodechar{ˣ}{\ensuremath{{}^{x}}}
\newunicodechar{ʸ}{\ensuremath{{}^{y}}}
\newunicodechar{ᶻ}{\ensuremath{{}^{z}}}
\newunicodechar{ᴬ}{\ensuremath{{}^{A}}}
\newunicodechar{ᴮ}{\ensuremath{{}^{B}}}
\newunicodechar{ᴰ}{\ensuremath{{}^{D}}}
\newunicodechar{ᴱ}{\ensuremath{{}^{E}}}
\newunicodechar{ᴳ}{\ensuremath{{}^{G}}}
\newunicodechar{ᴴ}{\ensuremath{{}^{H}}}
\newunicodechar{ᴵ}{\ensuremath{{}^{I}}}
\newunicodechar{ᴶ}{\ensuremath{{}^{J}}}
\newunicodechar{ᴷ}{\ensuremath{{}^{K}}}
\newunicodechar{ᴸ}{\ensuremath{{}^{L}}}
\newunicodechar{ᴹ}{\ensuremath{{}^{M}}}
\newunicodechar{ᴺ}{\ensuremath{{}^{N}}}
\newunicodechar{ᴼ}{\ensuremath{{}^{O}}}
\newunicodechar{ᴾ}{\ensuremath{{}^{P}}}
\newunicodechar{ᴿ}{\ensuremath{{}^{R}}}
\newunicodechar{ᵀ}{\ensuremath{{}^{T}}}
\newunicodechar{ᵁ}{\ensuremath{{}^{U}}}
\newunicodechar{ⱽ}{\ensuremath{{}^{V}}}
\newunicodechar{ᵂ}{\ensuremath{{}^{W}}}
#+end_src
** Other                                       :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Other subscripts and superscripts
%---------------------------------------------------------------------
\newunicodechar{⁺}{\ensuremath{{}^{+}}}
\newunicodechar{₊}{\ensuremath{{}_{+}}}
#+end_src

* Other letters, letter-like characters         :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Other letter-like characters
%---------------------------------------------------------------------
\newunicodechar{ℓ}{\ensuremath{\mathrm{ℓ}}}
#+end_src

* Punctuation and parentheses                   :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Punctuation and parentheses
%---------------------------------------------------------------------
\newunicodechar{…}{\ensuremath{\mathrm{…}}}
\newunicodechar{⋯}{\ensuremath{\mathrm{⋯}}}
\newunicodechar{∶}{\ensuremath{\mathrm{∶}}}
\newunicodechar{∙}{\ensuremath{\mathrm{∙}}}
\newunicodechar{｛}{\ensuremath{\mathrm{\{}}}
\newunicodechar{｝}{\ensuremath{\mathrm{\}}}}
\newunicodechar{⟨}{\ensuremath{\mathrm{⟨}}}
\newunicodechar{⟩}{\ensuremath{\mathrm{⟩}}}
\newunicodechar{–}{\ensuremath{\mathrm{–}}}
\newunicodechar{—}{\ensuremath{\mathrm{—}}}
% As discussed here: https://tex.stackexchange.com/questions/486120/
% the prime characters are redefined by unicode-math at \begindocument.
% To redefine them, we need to override that.
% Unfortunately we then lose prime collapsing.
% The better solution is to use a font which has prime.
\AtBeginDocument{\newunicodechar{′}{'}}
\AtBeginDocument{\newunicodechar{″}{''}}
\AtBeginDocument{\newunicodechar{‴}{'''}}
\AtBeginDocument{\newunicodechar{⁗}{''''}}
#+end_src

I use unicode non-breaking spaces occasionally.
In LaTeX code, they should be translated to tildes.
#+begin_src latex
\newunicodechar{ }{~}
#+end_src

* Logical operators                             :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Logical operators
%---------------------------------------------------------------------
\newunicodechar{∀}{\ensuremath{\mathrm{∀}}}
\newunicodechar{∃}{\ensuremath{\mathrm{∃}}}
\newunicodechar{≡}{\ensuremath{\mathrm{≡}}}
\newunicodechar{≢}{\ensuremath{\mathrm{≢}}}
\newunicodechar{∧}{\ensuremath{\mathrm{∧}}}
\newunicodechar{∨}{\ensuremath{\mathrm{∨}}}
\newunicodechar{⇒}{\ensuremath{\mathrm{⇒}}}
\newunicodechar{⇐}{\ensuremath{\mathrm{⇐}}}
#+end_src

* Set theory operators                          :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Set theory operators
%---------------------------------------------------------------------
\newunicodechar{∈}{\ensuremath{\mathrm{∈}}}
\newunicodechar{∋}{\ensuremath{\mathrm{∋}}}
\newunicodechar{∅}{\ensuremath{\mathrm{∅}}}
\newunicodechar{∩}{\ensuremath{\mathrm{∩}}}
\newunicodechar{∪}{\ensuremath{\mathrm{∪}}}
\newunicodechar{⊎}{\ensuremath{\mathrm{⊎}}}
#+end_src

* Relational operators                          :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Relational operators
%---------------------------------------------------------------------
\newunicodechar{∘}{\ensuremath{\mathrm{∘}}}
\newunicodechar{≤}{\ensuremath{\mathrm{≤}}}
\newunicodechar{≥}{\ensuremath{\mathrm{≥}}}
\newunicodechar{≠}{\ensuremath{\mathrm{≠}}}
\newunicodechar{⊤}{\ensuremath{\mathrm{⊤}}}
\newunicodechar{⊥}{\ensuremath{\mathrm{⊥}}}
\newunicodechar{⊔}{\ensuremath{\mathrm{⊔}}}
\newunicodechar{⊓}{\ensuremath{\mathrm{⊓}}}
\newunicodechar{⊑}{\ensuremath{\mathrm{⊑}}}
#+end_src

* Other operators                               :incomplete:

#+begin_src latex
%---------------------------------------------------------------------
% Other operators
%---------------------------------------------------------------------
\newunicodechar{⊕}{\ensuremath{\mathrm{⊕}}}
\newunicodechar{⊗}{\ensuremath{\mathrm{⊗}}}
\newunicodechar{⊛}{\ensuremath{\mathrm{⊛}}}
\newunicodechar{⊘}{\ensuremath{\mathrm{⊘}}}
\newunicodechar{∣}{\ensuremath{\mathrm{∣}}}
\newunicodechar{∷}{\ensuremath{\mathrm{∷}}}
\newunicodechar{≟}{\ensuremath{\mathrm{≟}}}
\newunicodechar{≔}{\ensuremath{\mathrm{≔}}}
\newunicodechar{≈}{\ensuremath{\mathrm{≈}}}
\newunicodechar{⟶}{\ensuremath{\mathrm{⟶}}}
\newunicodechar{⇓}{\ensuremath{\mathrm{⇓}}}
#+end_src
